version: '3'

services:
  depcheck:
    image: depcheck:dev
    build:
      context: .
    ports:
      - 3000:80
      - 3001:3001
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: /bin/bash -c 'yarn install && yarn start'
